import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import NavProvider from "./context/navContext";
import Navbar from "./(components)/Navbar";
import LoadingScreenFirstOpen from "./(components)/LoadingScreenFirstOpen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Evan Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} w-full text-white`}>
        <NavProvider>
          <LoadingScreenFirstOpen />
          <Navbar />
          {children}
        </NavProvider>
      </body>
    </html>
  );
}
